name: Apigee Proxy Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'apiproxy/**'
  workflow_dispatch:

env:
  PROJECT_ID: 'vital-scout-430808-k8'  # Replace with your actual Google Cloud project ID

jobs:
  setup_and_auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          #token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: |
          gcloud info
          gcloud config list
          gcloud auth list

      - name: Debug Identity Token
        run: |
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"

  deploy_proxy:
    needs: setup_and_auth
    uses: apatilgtn/apigeex-proxy-ci-cd-main/.github/workflows/Reusable-proxy-deploy.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      proxy_name: 'WeatherForecastAPI'
      dev_env: 'dev'
      test_env: 'test'
      uat_env: 'uat'
      proxy-directory: 'apiproxy'
      repository: ${{ github.repository }}
    secrets:
      apigee_org: ${{ secrets.APIGEE_ORG }}
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
      service_account: ${{ secrets.SERVICE_ACCOUNT }}
