name: Apigee Proxy Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'apiproxy/**'
  workflow_dispatch:

jobs:
  API_Proxy_Deployment:
    uses: apatilgtn/apigeex-proxy-ci-cd-main/blob/main/.github/workflows/Reusable-proxy-deploy.yml@main
    permissions:
      contents: read
      id-token: write 
    with:
      proxy_name: 'WeatherForecastAPI'
      dev_env: 'dev'
      test_env: 'test'
      uat_env: 'uat'
      proxy-directory: 'apiproxy'
      repository: ${{ github.repository }}
    secrets:
      apigee_org: ${{ secrets.APIGEE_ORG }}
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
      service_account: ${{ secrets.SERVICE_ACCOUNT }}
